### ISSUE TITLE
Changing dropdown fields on the basis of zipcode change, disbables the submit button. 

### ISSUE THREAD

**Issue by saadurrehman-selectquote** [SelectQuoteLabs/SQForm#138]
https://www.loom.com/share/77b9622b601a4842bf2f252f034f9883

This seems an issue for me, The scenario is, when we type the zipcode, we need to set the state and county in the dropdown according to the API response, So i have to update the initialvalues of the SQForm so that it detects the value of dropdown, but it doesn't count it a new value.

code:::
`const [initialValues, setInitialValues] = React.useState(individualData); //passing the initialValue to the SQForm`

//on change of zipCode
//countyAndStatesOnZipChange (this is the response of API)
```
const {values} = = useSQFormContext();

setInitialValues({
        ...values, //so we don't get rid of current from values
        indv_state_id: countyAndStatesOnZipChange.StateId,
        indv_county: countyAndStatesOnZipChange.CountyName,
      });
```

**Comment by 20BBrown14** [comment]
In this case I don't think you want to reset the initialvalues. I believe that's what causing you issues. You're effectively resetting the form and thus the submit button will not be enabled. That's another issue, though.

What I thikn you want to do is peak in the `values` using `useSQFormContext` like you're already doing and get the state/county combo then use `setFieldValue` to set the value on those fields. `setFieldValue('someStateField', someState)` `setFieldValue('someCountyField', someCounty)`

Since you want to set more than one value at a time you can use `setValues` instead of `setFieldValue`

setFieldValue Docs: https://formik.org/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean--void
setValue Docs: https://formik.org/docs/api/formik#setvalues-fields-reactsetstateaction-field-string-any--shouldvalidate-boolean--void

**Comment by saadurrehman-selectquote** [comment]
Thanks @20BBrown14 it worked
