### ISSUE TITLE
SQFormDateTimePicker && SQFormDatePickerWithCalendarInputOnly not validating on date selection (with window picker)

### ISSUE THREAD

**Issue by caleboleary** [SelectQuoteLabs/SQForm#147]
Same issue as https://github.com/SelectQuoteLabs/SQForm/issues/127

When selecting an invalid date (defined by the yup schema) using only the datepicker (the only option in the `SQFormDatePickerWithCalendarInputOnly` variant) - error messages are not showing on change, only when you interact with the field a second time.

The same fix proposed in this https://github.com/SelectQuoteLabs/SQForm/pull/143/files PR didn't seem to fix the problem (though its probably a good start in the case of `SQFormDateTimePicker`).

I did a little more digging and wondered if it might be something to do with comparing a string of a date vs a moment date object or something, but I could be totally off base with that.

Here's a loom where I show both of them failing to validate and say a lot of this again: https://www.loom.com/share/427a01cf8c0546f4ac96182fb5eac068

**Comment by codyarose** [comment]
I think the fix from that PR on `SQFormDatePicker` isn't working because the `onClose` is being overwritten in the other components. For example, in `SQFormDatePickerWithCalendarInputOnly` a different `onClose` is being passed through `muiFieldProps`, so the `helpers.setTouched()` in `SQFormDatePicker` will never run.
