### ISSUE TITLE
SQFormDatePickerWithCalendarInputOnly showing invalid date as valid

### ISSUE THREAD

**Issue by saadurrehman-selectquote** [SelectQuoteLabs/SQForm#198]
https://www.loom.com/share/fa807f8e16204fbeb0ba9632a217c490

Project loom : https://www.loom.com/share/04e9aa06caf94ca283ed0a152bcf556f

SQFormDatePickerWithCalendarInputOnly showing invalid date as valid if i reopen the modal

**Comment by codyarose** [comment]
I believe the input isn't showing that it's invalid after resetting the form because you're missing `.required()` on `middleDate` in your schema. However, I think the main underlying issue is that the form isn't running validation again on the initial values of the form after resetting - until one of the fields is blurred.

Related to #199

**Comment by laurelbean** [comment]
Closing this since it's been a while. Open a new issue if we find this happening again.
