### ISSUE TITLE
`SQFormAsyncAutocomplete` `handleAsyncInputChange` prop not required

### ISSUE THREAD

**Issue by codyarose** [SelectQuoteLabs/SQForm#208]
While writing the stories for `SQFormAsyncAutocomplete` I noticed the `handleAsyncInputChange` prop isn't required, but it's called whenever the input changes. So if the user doesn't provide the prop they'll get a `handleAsyncInputChange is not a function` error.

https://github.com/SelectQuoteLabs/SQForm/blob/c02dc9abc4b59eb63ad5b636e7216f41ece890ae/src/components/SQForm/SQFormAsyncAutocomplete.js#L142-L149

https://github.com/SelectQuoteLabs/SQForm/blob/c02dc9abc4b59eb63ad5b636e7216f41ece890ae/src/components/SQForm/SQFormAsyncAutocomplete.js#L223-L224

I think either a conditional should be added to check if the function exists before calling it, or it should be set to required in the proptypes. However, I haven't actually used this component in production, so I'll defer to someone with more experience with this to make the call on what to do here.

**Comment by lucas-homer** [comment]
This one takes me back! This is an example of an app that consumes this component, and I remember @SeanGroff and I developing this because I'd started using swr in the Med Screener Tool (aka Med Entry Tool)

```
export default function DrugAutocomplete({ name, handleSelectDrug }) {
  const [inputValue, setInputValue] = React.useState('');
  const { data: drugsList, isLoading } = useDrugSearch(inputValue);
  const [isOpen, setIsOpen] = React.useState(false);
  const [options, setOptions] = React.useState([]);

  React.useEffect(() => {
    if (isLoading) return;
    const drugOptions = getDrugOptions(drugsList);
    setOptions(drugOptions);
  }, [isLoading, drugsList]);

  return (
    <SQFormAsyncAutocomplete
      name={name}
      label="Med Name"
      isRequired
      size={3}
      handleAsyncInputChange={(value) => setInputValue(value)}
      open={isOpen}
      onOpen={() => setIsOpen(true)}
      onClose={() => setIsOpen(false)}
      loading={isLoading}
      onChange={handleSelectDrug}
    >
      {options}
    </SQFormAsyncAutocomplete>
  );
}
```

This is a super common pattern for us now, though. I think the best fix is to require this function. If you're consuming SQFormAsyncAutocomplete, that means the UX calls for a typeahead search, so we need an `onChange` passed down to the input that will update the consumer's local state, which is then passed to the query hook handling the search API request. Even if you aren't using `useQuery` you'd still want some way to update your search value at `onChange` (i.e. `handleAsyncInputChange`).

**Comment by lucas-homer** [comment]
one other thought -- we could arguably improve the naming of these props. 

Instead of `handleAsyncInputChange` we could call it `onInputChange`
Instead of `onChange` we could call it `onSelect`

But also, we could avoid breaking changes and simply improve our docs for the component. I guess that'd mean we need to get the docs deployed again 😬 @SeanGroff

**Comment by SeanGroff** [comment]
> one other thought -- we could arguably improve the naming of these props.
> 
> Instead of `handleAsyncInputChange` we could call it `onInputChange`
> Instead of `onChange` we could call it `onSelect`
> 
> But also, we could avoid breaking changes and simply improve our docs for the component. I guess that'd mean we need to get the docs deployed again 😬 @SeanGroff

While I'd prefer `onChange` over `handleChange` for a prop all day, I try to lean more towards avoiding the breaking change.

Def need to improve our docs but the quick win for this specific conundrum is TypeScript. With TypeScript, the developer would receive autocompletion of the component's props along with a description of that prop in a popover. within VS Code. If we use TSDoc or whatever, the user will also receive a description of that prop, much like we do with our docs format for prop-types in Storybook.

**Comment by lucas-homer** [comment]
So I pulled up the med screener tool code, ran it locally, and yeah, there IS a reason to have a separate `handleAsyncInputChange` different from `onInputChange` which is really a formik thing. So definitely we'd want to require this function prop. And to @SeanGroff 's point re: TS... agreed!
