### ISSUE TITLE
update Docs -- validationSchema should be Yup object not JS object literal

### ISSUE THREAD

**Issue by lucas-homer** [SelectQuoteLabs/SQForm#25]
ok cool! I think this should be added to our SQForm documentation because I've definitely not been doing it this way, but as you point out the Formik docs are clear on it

_Originally posted by @lucas-homer in https://github.com/SelectQuoteLabs/SQForm/pull/24#discussion_r544474827_

**Comment by SeanGroff** [comment]
SQForm accepts a POJO (Plain Old JS Object) for the `validationSchema` prop.
It then converts the POJO to `Yup.object().shape(validationSchema)`

<img width="470" alt="Screen Shot 2020-12-18 at 2 41 42 PM" src="https://user-images.githubusercontent.com/4367312/102659685-72d15a80-413f-11eb-921b-ea00c5e7884c.png">

Since our validation schemas will always be an object, I felt this was a nice abstraction to make.

To keep a consistent API I'm updating the Stepper component to also perform this conversion.

Changing this from a `documentation` issue to an `enhancement` issue.
