### ISSUE TITLE
DatePicker /w Date-FNS

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#251]
Create a solution that enables the consumers of SQForm to uses Date-FNS with our date picker components. We still need to support moment.js for backward compatibility. 

* Can we enhance our existing components without adding complexity?
* Or will it be less complex to create `SQFormDatePickerWithDateFNS.js`?

We would also need to update our documentation to show users how to add Date-FNS to the context provider that is required to wrap any application that uses SQFormDatePicker's.

The end goal is consumers no longer need to install `moment` to use SQFormDatePicker components

**Comment by codyarose** [comment]
I haven't set up this type of thing before, but from what I'm seeing in the Mui datepicker docs and in the SQForm codebase, it seems that all the users would need to do to make the SQForm datepickers work with `date-fns` is give the `DateFnsAdapter` to the `LocalizationProvider` instead of `MomentAdapter`. Then they'd need to migrate the use of `moment` to `date-fns` in their project.

Unless I'm missing something... ?

The only place SQForm uses `moment` is in [`src/utils/datetime.js`](https://github.com/SelectQuoteLabs/SQForm/blob/a0c7f74327cb255541819c7c6faf65c26a6759bd/src/utils/datetime.js), which actually isn't used anywhere.
```zsh
       summary               unimported v1.11.0
─────────────────────────────────────────────────────────────
       entry file          : src/index.js

       unresolved imports  : 0
       unused dependencies : 1
       unimported files    : 1


─────┬───────────────────────────────────────────────────────
     │ 1 unused dependencies
─────┼───────────────────────────────────────────────────────
   1 │ moment
─────┴───────────────────────────────────────────────────────


─────┬───────────────────────────────────────────────────────
     │ 1 unimported files
─────┼───────────────────────────────────────────────────────
   1 │ src/utils/datetime.js
─────┴───────────────────────────────────────────────────────
```

**Comment by SeanGroff** [comment]
@codyarose That's the hope! We attempted this with dayjs awhile back and ran into bugs with the library, specific to dayjs. Can we use MCE to test this out?

**Comment by codyarose** [comment]
> Can we use MCE to test this out? 

Sure! My use of moment is pretty minimal there, so it shouldn't take much to switch. It would be a small test of date-fns typescript support as well.
