### ISSUE TITLE
Height difference between SQFromTextField and SQFormDropdown

### ISSUE THREAD

**Issue by sarmadmishoo** [SelectQuoteLabs/SQForm#289]
As we aligned the textfields and dropdown horizontally feels height issue identified by Carlos Arroyo 

![141de74d-3e13-4646-b5e1-74c4ed987551](https://user-images.githubusercontent.com/32257805/120034834-12f8ad00-c017-11eb-986a-6db0518f7376.png)

**Comment by laurelbean** [comment]
This might have been solved with Issue #212 
What version are you using?

**Comment by sarmadmishoo** [comment]
we are using  "@selectquotelabs/sqform": "^4.5.0",

**Comment by laurelbean** [comment]
Looks like the issue I linked was added in 4.5.7 so yours should be getting that update. So looks like this is a new issue.

**Comment by 20BBrown14** [comment]
Just because the package-json says you're supposed to have the right version you might not be actually using the right version.

Update the package-json to ^4.5.7 and then `rm -rf node_modules && rm package-lock.json && npm i` to remove your current installed node_modules and get all new ones, the latest versions. And also rebuild your docker container if you're using one.

**Comment by sarmadmishoo** [comment]
@20BBrown14 @laurelbean Thanks Its been fixed by getting latest version.
