### ISSUE TITLE
SQFormScrollableCard isSelfBounding not working as expected

### ISSUE THREAD

**Issue by laurelbean** [SelectQuoteLabs/SQForm#436]
If the content in your SQFormScrollableCard is larger than the display area, then it doesn't convert to scrolling and you can't reach the submit / reset buttons or see all of the content.

Loom of issue: https://www.loom.com/share/71ba9e4e0d6e4ce1afec2f47eac3051c

I believe this error came in with 5.3.0 and has something to do with moving the height calculation to SQHooks.

**Comment by jamesgriffith9519** [comment]
I believe these two issues are related https://github.com/SelectQuoteLabs/SQHooks/issues/37#issuecomment-912119734

**Comment by lucas-homer** [comment]
now that we have [this SQHooks PR merged](https://github.com/SelectQuoteLabs/SQHooks/pull/38), we _should_ be able to address this issue by upgrading to latest SQHooks to get the benefits inside SQFormScrollableCard's usage of `useAutoHeight`. @jamesgriffith9519 reported there still seems to be an issue with storybook and picking up the ref correctly, but we're fairly confident that once we upgrade SQHooks, we should be able to fix the isSelfBounding issue out in the wild.

**Comment by lucas-homer** [comment]
More testing after merging the `useAutoHeight` PR shows SQFormScrollableCard still does not work as expected. This issue is holding MIAV back a bit, so I'm going to open a PR that basically reverts the usage of `useAutoHeight` and goes back to the inline solution that was there before, and worked as needed. We can revisit this issue in the future
