### ISSUE TITLE
Icon Submit button not submitting the form if form element have focus. 

### ISSUE THREAD

**Issue by sqwaheed** [SelectQuoteLabs/SQForm#491]
Loom Covers everything:

https://www.loom.com/share/807ef64c1cd44e99813efc8b3a391944

Re opening

**Comment by sqwaheed** [comment]
Loom with SQForm Storybook:
https://www.loom.com/share/d3f93cca416d4e888e56c2853a739447

**Comment by SeanGroff** [comment]
Hi @sqwaheed 
Thank you for the detailed issue report.

The issue is not with the Icon submit button, rather the focus behavior of the form fields. After making a selection in a form field, the focus should shift to the next form field, which should allow us to either interact with the next field or perform a form submit.

I'm going to update the issue details to reflect this.

Thanks

**Comment by SeanGroff** [comment]
I spoke with the PM of Pop Health (Vince) to let him know the solution for their project. 
The Text button does not have the issue reported in this issue.

From UI/UX 

"The green check button- our new designs have removed that and rely on “Submit” or “Save” to handle the submission"
"We should use a button that has an action that the user can read. We are staying away from icons in our UI"

Sean Groff  12:18 PM
In the next version of SQForm, i’m going to create a breaking change that removes the icon button from the library.
I’ll include migration instructions so the developer knows how to replace the icon button with the text button to adhere to our design best practices
Is this ok?

Carlos Arroyo  12:25 PM
Absolutely

Christina Lynn  12:27 PM
yesssss thank you!!
