### ISSUE TITLE
Update Shared Components version

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#630]
Update the scplus-shared-components & SQHooks dependencies to their latest versions

**Comment by aharpt** [comment]
@20BBrown14 @lucas-homer @laurelbean Is this issue fine to delete since we are updating our scplus-shared-components version as part of the MUI5 migration?  Honestly not totally sure what the latest state of SQHooks is...  Just thinking we might want to do some cleanup of old issues if they are no longer relevant.

**Comment by laurelbean** [comment]
Currently on the latest.
