### ISSUE TITLE
Fix validateDOMNesting when running test script

### ISSUE THREAD

**Issue by samasastudio** [SelectQuoteLabs/SQForm#838]
The validateDOMNesting error throws with every test suite run.  Taking a look at the stack trace, this is an issue that results from invalid element nesting in the `HelperTextComponent` that's used throughout.  This issue will track finding a fitting solution by perhaps rearranging how the text is nested so that this error doesn't throw anymore.

<img width="1130" alt="Screenshot 2023-02-07 at 11 43 25 AM" src="https://user-images.githubusercontent.com/55225884/217324106-86b0c460-65fd-4d73-883c-7e9bbbc986e2.png">

**Comment by 20BBrown14** [comment]
This issue is because we use the `helperText` prop on a lot of our fields to display the validation text on components. The helper text uses the `FormHelperText` component from MUI and by default uses a `<p>` component as the root component. 
Our validation text can sometimes render a `<Typography>` component which uses a `<p>` component by default.

If we change the root component of the Typographies with `component="span"` in the helper text, we can avoid this error and there appears to be no issues on the UI.

PR incoming.
